<project name="ant-sample" basedir="." default="run">

    <!-- properties -->
    <property name="src.dir"     value="src"/>
    <property name="build.dir"   value="build"/>
    <property name="classes.dir" value="${build.dir}/classes"/>
    <property name="jar.dir"     value="${build.dir}/jar"/>
    <property name="doc.dir"     value="doc"/>

    <!-- targets -->

    <target name="hello" description="hello desc">
        <echo message="Hello, Ant is working!" />
    </target>

    <target name="greet">
        <property name="username" value="TestUser"/>
        <echo message="Welcome, ${username}!" />
    </target>

    <target name="compile" description="compile project">
        <mkdir dir="${classes.dir}"/>
        <javac srcdir="${src.dir}" destdir="${classes.dir}" includeantruntime="false"/>
    </target>

    <target name="jar" depends="compile" description="generate the distribution jar">
        <mkdir dir="${jar.dir}"/>
        <jar destfile="${jar.dir}/${ant.project.name}.jar" basedir="${classes.dir}">
            <manifest>
                <attribute name="Main-Class" value="piona.Main"/>
            </manifest>
        </jar>
    </target>

    <target name="run" depends="compile" description="run application">       
            <java classname="piona.Gain"
              classpath="${classes.dir}"
              fork="true" />
    </target>

    <target name="build" depends="jar" description="build application"/>

    <target name="doc" description="generate documentation">
        <mkdir dir="${doc.dir}" />
        <javadoc destdir="${doc.dir}" sourcepath="${src.dir}"/>
    </target>

    <target name="clean" description="clean up build files">
        <delete dir="${build.dir}"/>
        <delete dir="${doc.dir}" />
    </target>

    <target name="rebuild" depends="clean,build" description="rebuild application"/>

</project>
